import type { Metadata } from "next";
import {
  Inter,
  Libre_Baskerville,
  Poppins,
  Roboto_Slab,
} from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/Sidebar/SidebarContext";
import BaseLayout from "@/components/Sidebar/BaseLayout";
import { ToastProvider, ToastViewport } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";

const roboto_slab = Roboto_Slab({ subsets: ["latin"] });

const poppin = Poppins({ subsets: ["latin"], weight: "400" });

const libre = Libre_Baskerville({ subsets: ["latin"], weight: ["400"] });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BPMP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative max-h-screen h-full">
          <div className="relative h-full">
            <SidebarProvider>
              <BaseLayout>
                {children}
                <Toaster />
              </BaseLayout>
            </SidebarProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
