import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "../components/Sidebar/SidebarContext";
import BaseLayout from "@/components/Sidebar/BaseLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BPMP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <BaseLayout>{children}</BaseLayout>
        </SidebarProvider>
      </body>
    </html>
  );
}
